=== SAP/abap-file-formats/file-formats/dsfi/dsfi-v1.json
{
  "$comment": "This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information.",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/SAP/abap-file-formats/blob/main/file-formats/dsfi/dsfi-v1.json",
  "title": "General Information",
  "type": "object",
  "properties": {
    "formatVersion": {
      "title": "ABAP File Format Version",
      "description": "The ABAP file format version",
      "type": "string",
      "const": "1"
    },
    "header": {
      "title": "Header",
      "description": "Header",
      "type": "object",
      "properties": {
        "description": {
          "title": "Description",
          "description": "Description of the ABAP object",
          "type": "string",
          "maxLength": 60
        },
        "originalLanguage": {
          "title": "Original Language",
          "description": "Original language of the ABAP object",
          "type": "string",
          "minLength": 2
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP language version",
          "type": "string",
          "enum": [
            "standard",
            "keyUser",
            "cloudDevelopment"
          ],
          "enumTitles": [
            "Standard",
            "ABAP for Key Users",
            "ABAP Cloud Development"
          ],
          "enumDescriptions": [
            "Standard",
            "ABAP for key user extensibility",
            "ABAP cloud development"
          ],
          "default": "standard"
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "originalLanguage"
      ]
    },
    "scalarFunctionName": {
      "title": "Scalar Function Name",
      "description": "The name of the scalar function",
      "type": "string",
      "maxLength": 30
    },
    "engine": {
      "title": "Engine",
      "description": "Engine",
      "type": "string",
      "enum": [
        "analyticalEngine",
        "sqlEngine"
      ],
      "enumTitles": [
        "Analytical Engine",
        "SQL Engine"
      ],
      "enumDescriptions": [
        "Analytical engine",
        "SQL engine"
      ],
      "default": "analyticalEngine"
    },
    "sqlProperties": {
      "title": "SQL Properties",
      "description": "SQL Properties",
      "type": "object",
      "properties": {
        "amdpFunctionImplementation": {
          "title": "AMDP Function Implementation",
          "description": "The name of the AMDP implementation reference",
          "type": "string",
          "maxLength": 100
        },
        "autoExposedInSqlServices": {
          "title": "Automatically Exposed in SQL Services",
          "description": "Flag whether or not the SQL implementation of the CDS scalar function will be automatically exposed in all SQL services",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "required": [
        "amdpFunctionImplementation"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "formatVersion",
    "header",
    "scalarFunctionName"
  ]
}

=== SAP/abap-file-formats/file-formats/dsfi/examples/z_aff_example_dsfi_sql.dsfi.json
{
  "formatVersion": "1",
  "header": {
    "description": "Example CDS scalar function",
    "originalLanguage": "en"
  },
  "scalarFunctionName": "Z_AFF_EXAMPLE_DSFI",
  "engine": "sqlEngine",
  "sqlProperties": {
    "amdpFunctionImplementation": "ZCL_DSFI_EXAMPLE=>EXECUTE",
    "autoExposedInSqlServices": true
  }
}
