=== SAP/abap-file-formats/file-formats/intm/intm-v1.json
{
  "$comment": "This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information.",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/SAP/abap-file-formats/blob/main/file-formats/intm/intm-v1.json",
  "title": "Intelligent scenario Models",
  "description": "Intelligent scenario Models",
  "type": "object",
  "properties": {
    "formatVersion": {
      "title": "Format Version",
      "description": "Format version",
      "type": "string",
      "const": "1"
    },
    "header": {
      "title": "Header",
      "description": "Header",
      "type": "object",
      "properties": {
        "description": {
          "title": "Description",
          "description": "Description of the ABAP object",
          "type": "string",
          "maxLength": 60
        },
        "originalLanguage": {
          "title": "Original Language",
          "description": "Original language of the ABAP object",
          "type": "string",
          "minLength": 2
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP language version",
          "type": "string",
          "enum": [
            "standard",
            "keyUser",
            "cloudDevelopment"
          ],
          "enumTitles": [
            "Standard",
            "ABAP for Key Users",
            "ABAP Cloud Development"
          ],
          "enumDescriptions": [
            "Standard",
            "ABAP for key user extensibility",
            "ABAP cloud development"
          ],
          "default": "standard"
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "originalLanguage"
      ]
    },
    "islmModelcc": {
      "title": "Intelligent Scenario Model",
      "description": "Intelligent Scenario Model",
      "type": "object",
      "properties": {
        "name": {
          "title": "Model Name",
          "description": "Model Name",
          "type": "string",
          "maxLength": 30
        },
        "parent": {
          "title": "Parent",
          "description": "Parent",
          "type": "string",
          "maxLength": 36
        },
        "description": {
          "title": "Model Description",
          "description": "Model Description",
          "type": "string"
        },
        "modelType": {
          "title": "Model Type",
          "description": "Model Type",
          "type": "string",
          "maxLength": 256
        },
        "adapterId": {
          "title": "Adapter ID",
          "description": "Adapter ID",
          "type": "string",
          "maxLength": 32
        },
        "nativeModelType": {
          "title": "Native Model Type",
          "description": "Native Model Type",
          "type": "string",
          "maxLength": 256
        },
        "modelSpecification": {
          "title": "Model Content",
          "description": "Model Content",
          "type": "string"
        },
        "modelDefinition": {
          "title": "Model definition",
          "description": "Model definition",
          "type": "string"
        },
        "state": {
          "title": "State of model",
          "description": "State of model",
          "type": "string",
          "maxLength": 10
        },
        "signature": {
          "title": "Signature",
          "description": "Signature",
          "type": "string"
        },
        "bindings": {
          "title": "Bindings",
          "description": "Bindings",
          "type": "string"
        },
        "newModel": {
          "title": "Model flag: Original = ' ', Enhancement = 'X'",
          "description": "New model?",
          "type": "boolean"
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP Language Version",
          "type": "string",
          "maxLength": 1
        }
      },
      "additionalProperties": false
    },
    "islmModel": {
      "title": "Model Details",
      "description": "Model Details",
      "type": "object",
      "properties": {
        "executableId": {
          "title": "Executable ID",
          "description": "Executable ID",
          "type": "string",
          "maxLength": 64
        },
        "llmName": {
          "title": "Large Language Model Name",
          "description": "Large Language Model Name",
          "type": "string"
        },
        "llmModelVersion": {
          "title": "LLM Model Version",
          "description": "LLM Model Version",
          "type": "string",
          "maxLength": 30
        }
      },
      "additionalProperties": false
    },
    "islmMdlsgmntfld": {
      "title": "Model Segment Fields",
      "description": "Model Segment Fields",
      "type": "array",
      "items": {
        "title": "Model Segment Fields",
        "description": "Model Segment Fields",
        "type": "object",
        "properties": {
          "fieldname": {
            "title": "Table or view field name",
            "description": "Table or view field name",
            "type": "string",
            "maxLength": 30
          },
          "fieldPosition": {
            "title": "Position",
            "description": "Position",
            "type": "integer",
            "minimum": -2147483648,
            "maximum": 2147483647
          },
          "isKey": {
            "title": "Key field Boolean flag?",
            "description": "Key field Boolean flag?",
            "type": "boolean"
          }
        },
        "additionalProperties": false
      }
    },
    "islmMdlprmttmpl": {
      "title": "Model Prompt Templates",
      "description": "Model Prompt Templates",
      "type": "array",
      "items": {
        "title": "Intelligent Scenario Model Prompt Template",
        "description": "Intelligent Scenario Model Prompt Template",
        "type": "object",
        "properties": {
          "name": {
            "title": "Prompt template name",
            "description": "Prompt template name",
            "type": "string",
            "maxLength": 30
          },
          "description": {
            "title": "Description",
            "description": "Description",
            "type": "string"
          },
          "prompt": {
            "title": "Prompt",
            "description": "Prompt",
            "type": "string"
          },
          "promptParameters": {
            "title": "Prompt Parameters",
            "description": "Prompt Parameters",
            "type": "string"
          },
          "visible": {
            "title": "Prompt Visibility",
            "description": "Prompt Visibility",
            "type": "boolean"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "prompt"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "formatVersion",
    "header",
    "islmModelcc",
    "islmModel"
  ]
}

=== SAP/abap-file-formats/file-formats/intm/examples/zlcc1zou8kmjs6ri88wmk474ph.intm.json
{
  "formatVersion": "1",
  "header": {
    "description": "Model created via ADT",
    "originalLanguage": "en"
  },
  "islmModelcc": {
    "name": "ZRM_TEST_ADT_002_MOD",
    "parent": "70A5DE7F2F83EE5C53AEFAC77E498F4A",
    "description": "Model created via ADT",
    "modelType": "SAPGENAI",
    "adapterId": "SAPGENAI.Default",
    "nativeModelType": "SAPGENAI.Default",
    "state": "Published"
  },
  "islmModel": {
    "executableId": "azure-openai",
    "llmName": "gpt-4",
    "llmModelVersion": "0613"
  },
  "islmMdlprmttmpl": [
    {
      "name": "SYSTEM_PROMPT",
      "description": "System prompt",
      "prompt": "You are a sales executive who is responsible for reaching out to customers for confirming or declining their orders. Evaluate the size of the delivery vehicle based on the number of items. Calculate the distance between the billing and delivery location in kilometers. \n\nThe subject of email should be of format <Confirmation on order number: {order_number} placed on {booking_date}> \nThe body of email should be of format: \"\"SO contains <Category> to be delivered to <Location>. And will be delivered via a <size> vehicle. \nIF <distance between source address and delivery address> > 100 kms THEN include a message about potential delivery delays ELSE congratulate on being eligible for one day delivery",
      "promptParameters": "[]"
    },
    {
      "name": "USER_PROMPT",
      "description": "User prompt",
      "prompt": "Build a confirmation mail for a sales order containing {ISLM_Items} where the items are categorized for example pencil and paper will be stationary, printer and mouse will be electronics. The source address contains {ISLM_Source} and the delivery address is in {ISLM_Destination}.",
      "promptParameters": "[{\"Name\":\"ISLM_Items\",\"Value\":\"\"},{\"Name\":\"ISLM_Source\",\"Value\":\"\"},{\"Name\":\"ISLM_Destination\",\"Value\":\"\"}]",
      "visible": true
    },
    {
      "name": "TEST_PROMPT_EDIT",
      "description": "To test prompt edit",
      "prompt": "What to do here?",
      "promptParameters": "[]",
      "visible": true
    }
  ]
}
