=== SAP/abap-file-formats/file-formats/susi/susi-v1.json
{
  "$comment": "This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information.",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/SAP/abap-file-formats/blob/main/file-formats/susi/susi-v1.json",
  "title": "SUSI Object Type",
  "description": "Object type SUSI",
  "type": "object",
  "properties": {
    "formatVersion": {
      "title": "ABAP File Format Version",
      "description": "The ABAP file format version",
      "type": "string",
      "const": "1"
    },
    "header": {
      "title": "Header",
      "description": "Header",
      "type": "object",
      "properties": {
        "description": {
          "title": "Description",
          "description": "Description of the ABAP object",
          "type": "string",
          "maxLength": 60
        },
        "originalLanguage": {
          "title": "Original Language",
          "description": "Original language of the ABAP object",
          "type": "string",
          "minLength": 2,
          "maxLength": 2,
          "pattern": "^[a-z]+$"
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP language version",
          "type": "string",
          "enum": [
            "standard",
            "cloudDevelopment"
          ],
          "enumTitles": [
            "Standard",
            "ABAP Cloud Development"
          ],
          "enumDescriptions": [
            "Standard",
            "ABAP cloud development"
          ],
          "default": "standard"
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "originalLanguage"
      ]
    },
    "generalInformation": {
      "title": "General Information",
      "description": "General information",
      "type": "object",
      "properties": {
        "applicationName": {
          "title": "Application Name",
          "description": "Application name of authorization default value",
          "type": "string",
          "maxLength": 132
        },
        "applicationType": {
          "title": "Application Type",
          "description": "Type of authorization default value.",
          "type": "string",
          "maxLength": 80
        },
        "maintenanceMode": {
          "title": "Maintenance Mode",
          "description": "Maintenance mode.",
          "type": "string",
          "enum": [
            "manual",
            "automatic",
            "automaticBasisObjects",
            "noDefaultValues",
            "deprecated",
            "obsolete"
          ],
          "enumTitles": [
            "Manual Maintenance",
            "Autom. Maintenance (All Objects)",
            "Automatic Maintenance (Basis Authorization Objects Only)",
            "Application Does Not Require Default Values",
            "Application is Deprecated",
            "Application Is Obsolete"
          ],
          "enumDescriptions": [
            "Manual maintenance",
            "Automatic maintenance (all objects)",
            "Automatic maintenance (basis authorization objects only)",
            "Application does not require default values",
            "Application is deprecated",
            "Application is obsolete"
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "applicationName",
        "applicationType",
        "maintenanceMode"
      ]
    },
    "authorizationObjects": {
      "title": "Authorization objects",
      "description": "Authorization objects",
      "type": "array",
      "items": {
        "title": "Authorization Objects Details",
        "description": "Authorization objects details",
        "type": "object",
        "properties": {
          "object": {
            "title": "Object",
            "description": "Name of authorization object",
            "type": "string",
            "maxLength": 10
          },
          "maintenanceStatus": {
            "title": "Maintenance Status",
            "description": "Maintenance status",
            "type": "string",
            "enum": [
              "noDefault",
              "defaultWithValues",
              "defaultWithoutValues",
              "inactiveValues",
              "unmaintainedValues",
              "authorizationCheckInactive"
            ],
            "enumTitles": [
              "No Default",
              "Default With Field Values",
              "Default Without Field Values",
              "Default Inactive",
              "Unmaintained Object Status",
              "Authorization Check Inactive"
            ],
            "enumDescriptions": [
              "No default",
              "Default with field values",
              "Default without field values",
              "Default inactive",
              "Unmaintained object status",
              "Authorization check inactive"
            ],
            "default": "defaultWithValues"
          },
          "fields": {
            "title": "Fields",
            "description": "Authorization fields.",
            "type": "array",
            "items": {
              "title": "Authorization Field Details",
              "description": "Authorization field details",
              "type": "object",
              "properties": {
                "field": {
                  "title": "Field",
                  "description": "Name of authorization field",
                  "type": "string",
                  "maxLength": 10
                },
                "low": {
                  "title": "From",
                  "description": "From value",
                  "type": "string",
                  "maxLength": 40
                },
                "high": {
                  "title": "To",
                  "description": "To values",
                  "type": "string",
                  "maxLength": 40
                }
              },
              "additionalProperties": false,
              "required": [
                "field"
              ]
            }
          }
        },
        "additionalProperties": false,
        "required": [
          "object",
          "maintenanceStatus"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "formatVersion",
    "header",
    "generalInformation"
  ]
}

=== SAP/abap-file-formats/file-formats/susi/examples/55fae0107acd2ee619d9f869c651edhs.susi.json
{
  "formatVersion": "1",
  "header": {
    "description": "SUSI Testobject",
    "originalLanguage": "en"
  },
  "generalInformation": {
    "applicationName": "WS SRT_TEST_WEBI/REQUEST_RESPONSE",
    "applicationType": "WebService",
    "maintenanceMode": "manual"
  },
  "authorizationObjects": [
    {
      "object": "S_SERVICE",
      "maintenanceStatus": "noDefault"
    },
    {
      "object": "S_DATASET",
      "maintenanceStatus": "defaultWithValues",
      "fields": [
        {
          "field": "ACTVT",
          "low": "33"
        },
        {
          "field": "ACTVT",
          "low": "34"
        },
        {
          "field": "PROGRAM",
          "low": "SAPLSTRF"
        }
      ]
    },
    {
      "object": "S_TABU_RFC",
      "maintenanceStatus": "defaultWithValues",
      "fields": [
        {
          "field": "ACTVT",
          "low": "03"
        }
      ]
    }
  ]
}
