=== SAP/abap-file-formats/file-formats/cdbo/cdbo-v1.json
{
  "$comment": "This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information.",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/SAP/abap-file-formats/blob/main/file-formats/cdbo/cdbo-v1.json",
  "title": "Customer Data Browser Object",
  "description": "Customer Data Browser Object",
  "type": "object",
  "properties": {
    "formatVersion": {
      "title": "Format Version",
      "description": "Format version",
      "type": "string",
      "const": "1"
    },
    "header": {
      "title": "Header",
      "description": "Header",
      "type": "object",
      "properties": {
        "description": {
          "title": "Description",
          "description": "Description of the ABAP object",
          "type": "string",
          "maxLength": 60
        },
        "originalLanguage": {
          "title": "Original Language",
          "description": "Original language of the ABAP object",
          "type": "string",
          "minLength": 2
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP language version",
          "type": "string",
          "enum": [
            "standard",
            "keyUser",
            "cloudDevelopment"
          ],
          "enumTitles": [
            "Standard",
            "ABAP for Key Users",
            "ABAP Cloud Development"
          ],
          "enumDescriptions": [
            "Standard",
            "ABAP for key user extensibility",
            "ABAP cloud development"
          ],
          "default": "standard"
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "originalLanguage"
      ]
    },
    "generalInformation": {
      "title": "General Information",
      "description": "General information",
      "type": "object",
      "properties": {
        "objectType": {
          "title": "Object Type",
          "description": "Object type",
          "type": "string",
          "enum": [
            "TABL",
            "DDLS"
          ],
          "enumTitles": [
            "Table",
            "Data Definition"
          ],
          "enumDescriptions": [
            "Table",
            "CDS data definition"
          ]
        },
        "objectName": {
          "title": "Object Name",
          "description": "Object name",
          "type": "string",
          "maxLength": 40
        }
      },
      "additionalProperties": false,
      "required": [
        "objectType",
        "objectName"
      ]
    },
    "fields": {
      "title": "Fields",
      "description": "Fields",
      "type": "array",
      "items": {
        "title": "Field Details",
        "description": "Field details",
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "description": "Name",
            "type": "string",
            "maxLength": 30
          },
          "nature": {
            "title": "Nature",
            "description": "Nature",
            "type": "string",
            "enum": [
              "general",
              "sensitive",
              "nonBusinessInformation"
            ],
            "enumTitles": [
              "General Information (No Sensitive Personal Information)",
              "Sensitive Personal Information",
              "Non Business Information"
            ],
            "enumDescriptions": [
              "General fields that do not contain sensitive personal information",
              "Sensitive personal information fields including key fields",
              "Non business information"
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "nature"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "formatVersion",
    "header",
    "generalInformation",
    "fields"
  ]
}

=== SAP/abap-file-formats/file-formats/cdbo/examples/zcdb_adt_test.cdbo.json
{
  "formatVersion": "1",
  "header": {
    "description": "CDBO on ADT Testing",
    "originalLanguage": "en"
  },
  "generalInformation": {
    "objectType": "TABL",
    "objectName": "ZCDB_ADT_TEST"
  },
  "fields": [
    {
      "name": "MANDT",
      "nature": "general"
    },
    {
      "name": "TIME",
      "nature": "general"
    },
    {
      "name": "DATUM",
      "nature": "general"
    }
  ]
}

=== SAP/abap-file-formats/file-formats/cdbo/examples/cdb_adt_test.cdbo.json
{
  "formatVersion": "1",
  "header": {
    "description": "Testing CDBO  saw2",
    "originalLanguage": "en",
    "abapLanguageVersion": "cloudDevelopment"
  },
  "generalInformation": {
    "objectType": "TABL",
    "objectName": "CDB_ADT_TEST"
  },
  "fields": [
    {
      "name": "CLIENT",
      "nature": "nonBusinessInformation"
    },
    {
      "name": "TIME",
      "nature": "general"
    },
    {
      "name": "DATUM",
      "nature": "general"
    }
  ]
}
