=== SAP/abap-file-formats/file-formats/edoi/edoi-v1.json
{
  "$comment": "This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information.",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/SAP/abap-file-formats/blob/main/file-formats/edoi/edoi-v1.json",
  "title": "eDocument Interface",
  "description": "eDocument interface",
  "type": "object",
  "properties": {
    "formatVersion": {
      "title": "Format Version",
      "description": "Format version",
      "type": "string",
      "const": "1"
    },
    "header": {
      "title": "Header",
      "description": "Header",
      "type": "object",
      "properties": {
        "description": {
          "title": "Description",
          "description": "Description of the ABAP object",
          "type": "string",
          "maxLength": 100
        },
        "originalLanguage": {
          "title": "Original Language",
          "description": "Original language of the ABAP object",
          "type": "string",
          "minLength": 2
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP language version",
          "type": "string",
          "enum": [
            "standard",
            "cloudDevelopment"
          ],
          "enumTitles": [
            "Standard",
            "ABAP Cloud Development"
          ],
          "enumDescriptions": [
            "Standard",
            "ABAP cloud development"
          ],
          "default": "standard"
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "originalLanguage"
      ]
    },
    "generalInformation": {
      "title": "General Information",
      "description": "General information",
      "type": "object",
      "properties": {
        "direction": {
          "title": "Direction",
          "description": "Interface direction",
          "type": "string",
          "enum": [
            "outbound",
            "inbound"
          ],
          "enumTitles": [
            "Outbound",
            "Inbound"
          ],
          "enumDescriptions": [
            "Outbound",
            "Inbound"
          ],
          "default": "outbound"
        }
      },
      "additionalProperties": false,
      "required": [
        "direction"
      ]
    },
    "versions": {
      "title": "Versions",
      "description": "Interface versions",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "title": "Version Details",
        "description": "eDocument interface version details",
        "type": "object",
        "properties": {
          "version": {
            "title": "Version",
            "description": "Version",
            "type": "integer",
            "minimum": 1,
            "maximum": 9999
          },
          "description": {
            "title": "Description",
            "description": "Description",
            "type": "string",
            "maxLength": 30
          },
          "activeFrom": {
            "title": "Active From",
            "description": "Active from",
            "type": "string",
            "format": "date"
          },
          "communicationAttributes": {
            "title": "Communication Integration Attributes",
            "description": "Communication integration attributes",
            "type": "object",
            "properties": {
              "processType": {
                "title": "Process Type",
                "description": "DRC process type",
                "type": "string",
                "maxLength": 50
              },
              "processVersion": {
                "title": "Process Version",
                "description": "DRC process version",
                "type": "string",
                "maxLength": 20
              },
              "processSubtype": {
                "title": "Process Subtype",
                "description": "DRC process subtype",
                "type": "string",
                "maxLength": 50
              },
              "drcAction": {
                "title": "Action",
                "description": "DRC process action",
                "type": "string",
                "maxLength": 30
              },
              "responseInterface": {
                "title": "Response Interface",
                "description": "eDoc response interface",
                "type": "string",
                "maxLength": 30
              },
              "responseInterfaceVersion": {
                "title": "Response Interface Version",
                "description": "Response interface version",
                "type": "integer",
                "minimum": 1,
                "maximum": 9999
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false,
        "required": [
          "version",
          "description",
          "activeFrom"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "formatVersion",
    "header",
    "generalInformation",
    "versions"
  ]
}

=== SAP/abap-file-formats/file-formats/edoi/examples/z_aff_example_edoi.edoi.json
{
  "formatVersion": "1",
  "header": {
    "description": "France: Customer Invoice Request",
    "originalLanguage": "en"
  },
  "generalInformation": {
    "direction": "outbound"
  },
  "versions": [
    {
      "version": 1,
      "description": "Initial Version",
      "activeFrom": "01.01.2025",
      "communicationAttributes": {
        "processType": "CUSTOMER_INVOICE",
        "processVersion": "1.0.0",
        "processSubtype": "DOMESTIC",
        "drcAction": "TRANSMIT",
        "responseInterface": "INVOICER",
        "responseInterfaceVersion": 1
      }
    },
    {
      "version": 2,
      "description": "Version 2",
      "activeFrom": "01.07.2025",
      "communicationAttributes": {
        "processType": "CUSTOMER_INVOICE",
        "processVersion": "1.1.0",
        "processSubtype": "DOMESTIC",
        "drcAction": "TRANSMIT",
        "responseInterface": "INVOICER",
        "responseInterfaceVersion": 2
      }
    }
  ]
}
