=== SAP/abap-file-formats/file-formats/doma/doma-v2.json
{
  "$comment": "This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information.",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/SAP/abap-file-formats/blob/main/file-formats/doma/doma-v2.json",
  "title": "Domain Properties",
  "description": "Domain properties",
  "type": "object",
  "properties": {
    "formatVersion": {
      "title": "ABAP File Format Version",
      "description": "The ABAP file format version",
      "type": "string",
      "const": "2"
    },
    "header": {
      "title": "Header",
      "description": "Header",
      "type": "object",
      "properties": {
        "description": {
          "title": "Description",
          "description": "Description of the ABAP object",
          "type": "string",
          "maxLength": 60
        },
        "originalLanguage": {
          "title": "Original Language",
          "description": "Original language of the ABAP object",
          "type": "string",
          "minLength": 2
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP language version",
          "type": "string",
          "enum": [
            "standard",
            "keyUser",
            "cloudDevelopment"
          ],
          "enumTitles": [
            "Standard",
            "ABAP for Key Users",
            "ABAP Cloud Development"
          ],
          "enumDescriptions": [
            "Standard",
            "ABAP for key user extensibility",
            "ABAP cloud development"
          ],
          "default": "standard"
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "originalLanguage"
      ]
    },
    "dataType": {
      "type": "string",
      "enum": [
        "postingPeriod",
        "characterString",
        "client",
        "currencyKey",
        "currencyField",
        "floatingPoint16Dec",
        "floatingPoint16Raw",
        "floatingPoint16Scl",
        "floatingPoint34Dec",
        "floatingPoint34Raw",
        "floatingPoint34Scl",
        "date",
        "counterOrAmount",
        "floatingPoint",
        "integer1",
        "integer2",
        "integer4",
        "languageIe6",
        "longString",
        "longByteString",
        "numericCharacter",
        "obsoletePrec",
        "quantity",
        "byteSequence",
        "byteString",
        "shortString",
        "string",
        "time",
        "unit",
        "obsoleteVarc"
      ],
      "enumTitles": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    },
    "length": {
      "title": "No Characters",
      "description": "Number of characters",
      "type": "integer",
      "minimum": 0,
      "maximum": 999999
    },
    "decimals": {
      "description": "Set if decimal",
      "type": "integer",
      "minimum": 0,
      "maximum": 999999
    },
    "negativeValues": {
      "title": "Supports Negative Values",
      "description": "Supports negative values",
      "type": "boolean"
    },
    "caseSensitive": {
      "title": "Case Sensitive",
      "description": "Values are case sensitive",
      "type": "boolean"
    },
    "outputLength": {
      "description": "Set the output length",
      "type": "integer",
      "minimum": 0,
      "maximum": 999999
    },
    "conversionRoutine": {
      "description": "Conversion Routine",
      "type": "string",
      "maxLength": 5
    },
    "valueTable": {
      "description": "Value table",
      "type": "string",
      "maxLength": 30
    },
    "fixedValues": {
      "description": "Fixed values",
      "type": "array",
      "items": {
        "title": "Single Values",
        "description": "Single values",
        "type": "object",
        "properties": {
          "fixedValue": {
            "title": "Fixed Value",
            "description": "Value",
            "type": "string",
            "maxLength": 10
          },
          "description": {
            "title": "Description",
            "description": "Description",
            "type": "string",
            "maxLength": 60
          }
        },
        "additionalProperties": false
      }
    },
    "fixedValueIntervals": {
      "description": "Fixed value intervals",
      "type": "array",
      "items": {
        "title": "Interval Values",
        "description": "Interval values",
        "type": "object",
        "properties": {
          "lowLimit": {
            "title": "Low Limit of the Interval",
            "description": "Low value for the interval",
            "type": "string",
            "maxLength": 10
          },
          "highLimit": {
            "title": "High Limit of the Interval",
            "description": "High value for the interval",
            "type": "string",
            "maxLength": 10
          },
          "description": {
            "title": "Description",
            "description": "Description",
            "type": "string",
            "maxLength": 60
          }
        },
        "additionalProperties": false,
        "required": [
          "highLimit"
        ]
      }
    },
    "fixedValueAppends": {
      "description": "Fixed value appends",
      "type": "array",
      "items": {
        "title": "Object Name",
        "description": "Object name with max. length 30",
        "type": "string",
        "maxLength": 30
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "formatVersion",
    "header",
    "dataType",
    "length"
  ]
}

=== SAP/abap-file-formats/file-formats/doma/examples/z_aff_example_v2.doma.json
{
  "formatVersion": "2",
  "header": {
    "description": "Example DOMA for ABAP file formats",
    "originalLanguage": "en"
  },
  "dataType": "characterString",
  "length": 3,
  "outputLength":3,
  "fixedValues": [
    {
      "fixedValue": "ABC",
      "description": "Fixed value ABC"
    },
    {
      "fixedValue": "XYZ",
      "description": "Fixed value XYZ"
    }
  ]
}
